dist: jammy

branches:
  only:
    - master

language: ruby
rvm:
  - 3.2

before_script:
  - gem install awesome_bot
script:
  # NB: it's impossible to automatically check youtube.com links, as
  # Google detects that as malicious activity and redirects to CAPTCHA at
  # https://google.com/sorry/...
  - awesome_bot --white-list youtube.com README.md
notifications:
  email: false
