name: awesome_bot

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # NB: it's impossible to automatically check youtube.com links, as
      # Google detects that as malicious activity and redirects to CAPTCHA at
      # https://google.com/sorry/...
      - uses: docker://dkhamsing/awesome_bot:latest
        with:
          args: --white-list youtube.com README.md
